### ISSUE TITLE
Please publish repository for Helm Chart

### ISSUE THREAD

**Issue by dekimasoon** [oxyno-zeta/postgresql-operator#24]
## Is your feature request related to a problem? Please describe.

Thank you for the great project.
I would love to use this Operator, but I noticed that there is no repository for Helm Chart.

A similar project has a public repository for Helm Chart, which can be easily installed as follows:

```
helm repo add ext-postgres-operator https://movetokube.github.io/postgres-operator/
helm install -n operators ext-postgres-operator ext-postgres-operator/ext-postgres-operator
```

Is there any chance that you could publish a Helm Chart repository that would allow for easy installation? 
Or is there already a repository for Helm Chart that I haven't found?

## Describe the solution you'd like

A repository for Helm Chart will be released to make installation easier.

## Describe alternatives you've considered

Clone the git repository.

**Comment by oxyno-zeta** [comment]
Hello, thanks for your issue. We know about this (we are copying it too...). We will try to work on this soon. Thanks !

**Comment by oxyno-zeta** [comment]
Hello @dekimasoon ,

We just release our Helm chart repository !

Thanks for your issue.
